import * as vscode from 'vscode';

export interface KarateTemplate {
    id: string;
    name: string;
    content: string;
    description: string;
    isCustom: boolean;
}

export class TemplateManager {
    private static readonly CUSTOM_TEMPLATES_KEY = 'karateDsl.customTemplates';

    private static readonly PRESET_TEMPLATES: KarateTemplate[] = [
        {
            id: 'standard',
            name: 'Standard',
            description: 'Balanced template with base URL and common assertions',
            isCustom: false,
            content: `Feature: {{featureName}}
  {{featureDescription}}

  Background:
    Given url baseUrl
{{backgroundSteps}}

{{scenarios}}`
        },
        {
            id: 'detailed',
            name: 'Detailed',
            description: 'Verbose template with headers, comments, and extensive validation',
            isCustom: false,
            content: `Feature: {{featureName}}
  # Generated by Karate DSL Generator
  # Source: {{source}}
  {{featureDescription}}

  Background:
    Given url baseUrl
    * configure headers = { 'Content-Type': 'application/json', 'Accept': 'application/json' }
{{backgroundSteps}}

{{scenarios}}`
        },
        {
            id: 'minimal',
            name: 'Minimal',
            description: 'Clean and compact template with only essential steps',
            isCustom: false,
            content: `Feature: {{featureName}}

  Background:
    Given url baseUrl

{{scenarios}}`
        }
    ];

    constructor(private readonly context: vscode.ExtensionContext) { }

    public getAllTemplates(): KarateTemplate[] {
        const customTemplates = this.context.globalState.get<KarateTemplate[]>(TemplateManager.CUSTOM_TEMPLATES_KEY, []);
        return [...TemplateManager.PRESET_TEMPLATES, ...customTemplates];
    }

    public getTemplate(id: string): KarateTemplate | undefined {
        return this.getAllTemplates().find(t => t.id === id);
    }

    public async saveCustomTemplate(template: Omit<KarateTemplate, 'isCustom' | 'isDefault'>): Promise<void> {
        const customTemplates = this.context.globalState.get<KarateTemplate[]>(TemplateManager.CUSTOM_TEMPLATES_KEY, []);
        const newTemplate: KarateTemplate = {
            ...template,
            isCustom: true
        };

        const index = customTemplates.findIndex(t => t.id === template.id);
        if (index >= 0) {
            customTemplates[index] = newTemplate;
        } else {
            customTemplates.push(newTemplate);
        }

        await this.context.globalState.update(TemplateManager.CUSTOM_TEMPLATES_KEY, customTemplates);
    }

    public async deleteCustomTemplate(id: string): Promise<void> {
        const customTemplates = this.context.globalState.get<KarateTemplate[]>(TemplateManager.CUSTOM_TEMPLATES_KEY, []);
        const filtered = customTemplates.filter(t => t.id !== id);
        await this.context.globalState.update(TemplateManager.CUSTOM_TEMPLATES_KEY, filtered);
    }
}
